# Generated by cucumber-sinatra. (2014-05-14 10:57:32 +0100)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', './lib/ajaxProject.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'

Capybara.app = ajaxProject

class ajaxProjectWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  ajaxProjectWorld.new
end
